# .github/workflows/docker-build-push.yml

name: Docker Build and Push

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  DOCKER_IMAGE_NAME: stremio-tamilshows # Name of your Docker image
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub access token/password

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for Git tag parsing

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Get current date for timestamp tag
      id: date
      run: echo "::set-output name=date_tag::$(date +'%Y%m%d%H%M')"

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.date.outputs.date_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

